#ifndef CONSTANTS_H
#define CONSTANTS_H

#define W_WINDOW 1280
#define H_WINDOW 1000

#define PLAYER_SPRITESHEET "./res/marisa-sheet.png"
#define DEFAULT_PLAYER_BULLET_PNG "./res/marisa-shot.png"
#define DEFAULT_PLAYER_BULLET_W 28
#define DEFAULT_PLAYER_BULLET_H 62
#define DEFAULT_PLAYER_BULLET_INIT_SPEED 3
#define PLAYER_SPRITESHEET_PIXELS 64
#define PLAYER_SPRITESHEET_NROWS 3
#define PLAYER_SPRITESHEET_NCOLS 8
#define PLAYER_N_ANIMS 3
#define PLAYER_ANIM_IDLE 0
#define PLAYER_ANIM_RIGHT 1
#define PLAYER_ANIM_LEFT 2
#define DEFAULT_PLAYER_SPEED 12
#define PLAYER_BULLET_SPEED 1.01

#define DEFAULT_ENEMY_SPRITESHEET "./res/enemy-idle.png"
#define DEFAULT_ENEMY_SPRITESHEET_NROWS 1
#define DEFAULT_ENEMY_SPRITESHEET_NCOLS 5
#define DEFAULT_ENEMY_SPRITE_W 60
#define DEFAULT_ENEMY_SPRITE_H 52
#define DEFAULT_ENEMY_SPEED 0.15
#define DEFAULT_ENEMY_PNG "./res/enemy-default.png"
#define DEFAULT_ENEMY_BULLET_PNG "./res/eshot1.bmp"
#define DEFAULT_ENEMY_BULLET_W 12
#define DEFAULT_ENEMY_BULLET_H 12
#define DEFAULT_ENEMY_BULLET_SPEED 0.25

#define DEFAULT_ENTITY_SPEED 12

#define DEFAULT_BG_PATH "./res/x68k_03.jpg"

#endif